on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'psalm.xml'

  push:
    branches: [ 'master' ]
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'psalm.xml'

name: Run tests

jobs:
  tests:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
          - '8.1'
          - '8.2'
          - '8.3'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          make generate-mongo-key
          sudo chmod 400 ./mongo-key.key
          ls -la mongo-key.key
          sleep 5
          make build v=${{ matrix.php }}
        shell: bash

      - name: Debug
        run: docker ps -a

      - name: Container logs
        run: docker logs db-mongodb-db-primary

      - name: Create cluster
        run: make create-cluster-mongodb

      - name: Run tests with phpunit
        run: make test v=${{ matrix.php }}
